version: 2

always_pending:
  title_regex: 'WIP'

groups:
  code-review:
    approve_by_comment:
      enabled: true
      approve_regex: '^(Approved|:shipit:|:\+1:|LGTM)'
      reject_regex: '^(Rejected|:-1:)'
    required: 1
    reset_on_push: false
    users:
    - jiyeonseo